"""
qsarena.reliability_tables — render the reliability study's per-dataset table for the manuscript.

Reads ``applicability_domain.csv`` and ``calibration.csv`` written by
``qsarena.reliability_study`` and emits the same table as LaTeX (Additional file 1, Table S8)
and as Markdown (manuscript.md supplementary section). Never hand-edit either output; rerun:

    python -m qsarena.reliability_tables --study results/reliability_tdc22 \
        --latex submission/tables/tableS8_applicability_domain.tex \
        --markdown results/reliability_tdc22/tableS8_applicability_domain.md
"""

from __future__ import annotations

import argparse
import math
import sys
from pathlib import Path

import pandas as pd

from qsarena.reliability_study import MIN_GROUP

__all__ = ["build_table", "to_latex", "to_markdown", "main"]

CAPTION = (
    "Applicability domain and calibration on the 22 official TDC ADMET Benchmark Group splits, for a "
    "fixed reference model (random forest, 300 trees, on Morgan radius-2 2048-bit fingerprints plus RDKit 2D "
    "descriptors) fitted to 80\\% of each train\\_val partition, with the remaining 20\\% used only for "
    "conformal calibration. Coverage is the fraction of test compounds inside the domain. The error ratio "
    "is the mean test error outside the domain divided by that inside it (MAE for regression, 0/1 error "
    "for classification); values above 1 mean the domain flag separates worse predictions. "
    "``Std.'' is the Roy standardization approach on RDKit descriptors; ``kNN'' is the 5-nearest-neighbour "
    "Tanimoto distance thresholded at the 95th percentile of training distances; ``Reliability'' is the "
    "conformal-interval-width flag (regression) or the posterior-probability confidence flag with "
    "$|p_1-p_0|\\ge 0.5$ (classification). Conformal coverage is the empirical test coverage of 90\\% "
    "split-conformal intervals or prediction sets. ``---'' marks a ratio not reported because fewer than "
    "five test compounds fall on one side of the domain boundary. Results describe the reference model, not the benchmark's selected model; single seed."
)

_RELIABILITY = {"regression": "conformal_interval_width", "classification": "probability_confidence"}


def build_table(study_dir: str | Path) -> pd.DataFrame:
    study_dir = Path(study_dir)
    ad = pd.read_csv(study_dir / "applicability_domain.csv")
    cal = pd.read_csv(study_dir / "calibration.csv")
    primary = ad[((ad.task == "regression") & (ad.error_metric == "mae"))
                 | ((ad.task == "classification") & (ad.error_metric == "error_rate"))]
    rows = []
    for _, c in cal.sort_values(["task", "dataset"], ascending=[False, True]).iterrows():
        sub = primary[primary.dataset == c.dataset].set_index("ad_method")
        sub = sub.assign(error_ratio_out_in=sub["error_ratio_out_in"].where(
            (sub["n_in"] >= MIN_GROUP) & (sub["n_out"] >= MIN_GROUP)))
        rel = sub.loc[_RELIABILITY[c.task]]
        rows.append({
            "Dataset": c.dataset,
            "Task": "reg." if c.task == "regression" else "cls.",
            "n test": int(c.n_test),
            "Std. coverage": sub.loc["standardization", "coverage"],
            "Std. ratio": sub.loc["standardization", "error_ratio_out_in"],
            "kNN coverage": sub.loc["knn_tanimoto", "coverage"],
            "kNN ratio": sub.loc["knn_tanimoto", "error_ratio_out_in"],
            "Reliability ratio": rel["error_ratio_out_in"],
            "Conformal coverage": c.conformal_coverage,
            "ECE": c.get("ece_10bin", float("nan")),
        })
    return pd.DataFrame(rows)


def _fmt(v, digits=2) -> str:
    if v is None or (isinstance(v, float) and math.isnan(v)):
        return "---"
    if isinstance(v, (int,)) and not isinstance(v, bool):
        return str(v)
    return f"{float(v):.{digits}f}"


def to_latex(table: pd.DataFrame) -> str:
    cols = list(table.columns)
    head = " & ".join(f"\\textbf{{{c}}}" for c in cols) + " \\\\"
    lines = [
        "%% Generated by python -m qsarena.reliability_tables -- do not edit by hand.",
        "\\begingroup\\scriptsize",
        "\\begin{xltabular}{\\linewidth}{@{}>{\\raggedright\\arraybackslash}Xl" + "r" * (len(cols) - 2) + "@{}}",
        f"\\caption{{{CAPTION}}}\\label{{tab:s8}}\\\\",
        "\\toprule", head, "\\midrule", "\\endfirsthead",
        "\\toprule", head, "\\midrule", "\\endhead",
        "\\bottomrule", "\\endlastfoot",
    ]
    for _, r in table.iterrows():
        cells = [r["Dataset"].replace("_", "\\_\\allowbreak{}"), r["Task"], str(int(r["n test"]))]
        cells += [_fmt(r[c]) for c in cols[3:]]
        lines.append(" & ".join(cells) + " \\\\")
    lines += ["\\end{xltabular}", "\\endgroup", ""]
    return "\n".join(lines)


def to_markdown(table: pd.DataFrame) -> str:
    cols = list(table.columns)
    out = ["| " + " | ".join(cols) + " |", "|" + "|".join(["---"] * 2 + ["---:"] * (len(cols) - 2)) + "|"]
    for _, r in table.iterrows():
        cells = [f"`{r['Dataset']}`", r["Task"], str(int(r["n test"]))] + [_fmt(r[c]).replace("---", "—") for c in cols[3:]]
        out.append("| " + " | ".join(cells) + " |")
    return "\n".join(out) + "\n"


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="Render the reliability study table.")
    p.add_argument("--study", type=Path, default=Path("results/reliability_tdc22"))
    p.add_argument("--latex", type=Path, default=Path("submission/tables/tableS8_applicability_domain.tex"))
    p.add_argument("--markdown", type=Path, default=Path("results/reliability_tdc22/tableS8_applicability_domain.md"))
    args = p.parse_args(argv)
    table = build_table(args.study)
    args.latex.write_text(to_latex(table), encoding="utf-8")
    args.markdown.write_text(to_markdown(table), encoding="utf-8")
    print(f"wrote {args.latex} and {args.markdown} ({len(table)} rows)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
